### ISSUE TITLE
你这个方式android没问题，但是ios上不显示，请指教

### ISSUE THREAD

**Issue by itshu** [Story5/qrscannerdemo#1]
ios背景不透明。

**Comment by Story5** [comment]
确实是的,当时主要在android上测试了.目前还没有研究iOS上qrscanner的应用.
iOS上我用的是另一个插件[Barcode Scanner](http://ionicframework.com/docs/native/barcode-scanner/)

**Comment by itshu** [comment]
但是Barcode Scanner样式不好控制，还得加一些功能按钮在上面，我搞了一周了，崩溃了要

**Comment by Story5** [comment]
@itshu 新发布qrscanner的2.6.0解决了ios上的这些问题,也许能够帮到你

**Comment by Story5** [comment]
地址 [https://github.com/bitpay/cordova-plugin-qrscanner](https://github.com/bitpay/cordova-plugin-qrscanner)
